### ISSUE TITLE
Program crashes when "null" is put in data file

### ISSUE THREAD

**Issue by antonTan96** [antonTan96/pe#3]
When modifying the `addressbook.json` file so that it contains `null` on the first line, the program will not start and the following message will appear.
```
Exception in Application init method
Exception in thread "main" java.lang.RuntimeException: Exception in Application init method
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:896)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:233)
        at java.base/java.util.Optional.of(Optional.java:113)
        at seedu.address.commons.util.JsonUtil.readJsonFile(JsonUtil.java:77)
        at seedu.address.storage.JsonAddressBookStorage.readAddressBook(JsonAddressBookStorage.java:48)
        at seedu.address.storage.StorageManager.readAddressBook(StorageManager.java:64)
        at seedu.address.storage.StorageManager.readAddressBook(StorageManager.java:58)
        at seedu.address.MainApp.initModelManager(MainApp.java:81)
        at seedu.address.MainApp.init(MainApp.java:63)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:825)
        ... 2 more
```

**Comment by nus-pe-script** [comment]
# Team's Response
[Not in scope](https://github.com/nus-cs2103-AY2324S1/forum/issues/510) as we did not state that it was a feature in the UG.
# Items for the Tester to Verify
## :question: Issue response

Team chose [`response.NotInScope`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your explanation]

<catcher-end-of-segment><hr>
